"""add league sync from

Revision ID: 123cb6a04530
Revises: 2c2ae180eb8b
Create Date: 2026-08-17 17:17:53.859257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123cb6a04530'
down_revision: Union[str, Sequence[str], None] = '2c2ae180eb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('sync_from', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'sync_from')
    # ### end Alembic commands ###
