"""fix biwenger league uniqueness

Revision ID: 1eaeca49dbc0
Revises: c0a9f887570c
Create Date: 2026-08-17 12:00:45.770062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eaeca49dbc0'
down_revision: Union[str, Sequence[str], None] = 'c0a9f887570c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_leagues_biwenger_league_id'), 'leagues', type_='unique')
    op.create_unique_constraint('uq_leagues_season_id_biwenger_league_id', 'leagues', ['season_id', 'biwenger_league_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_leagues_season_id_biwenger_league_id', 'leagues', type_='unique')
    op.create_unique_constraint(op.f('uq_leagues_biwenger_league_id'), 'leagues', ['biwenger_league_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
