"""add movement external key

Revision ID: 2c2ae180eb8b
Revises: 1eaeca49dbc0
Create Date: 2026-08-17 13:13:01.969517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2ae180eb8b'
down_revision: Union[str, Sequence[str], None] = '1eaeca49dbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('external_key', sa.String(length=64), nullable=True))
    op.create_unique_constraint(
    'uq_movements_external_key',
    'movements',
    ['external_key'],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    'uq_movements_external_key',
    'movements',
    type_='unique',
    )
    op.drop_column('movements', 'external_key')
    # ### end Alembic commands ###
