"""create movements

Revision ID: 919fd02a25d4
Revises: 385edc3977b1
Create Date: 2026-08-08 14:54:03.286756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919fd02a25d4'
down_revision: Union[str, Sequence[str], None] = '385edc3977b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_participant_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE', 'SALE', 'BONUS', 'CLAUSE_COMPENSATION', 'ADJUSTMENT', name='movement_type'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('player_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_participant_id'], ['season_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movements')
    # ### end Alembic commands ###
