"""add round bonus and sync tracking

Revision ID: acf95ccb42b8
Revises: 123cb6a04530
Create Date: 2026-08-31 16:16:49.199531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf95ccb42b8'
down_revision: Union[str, Sequence[str], None] = '123cb6a04530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Añadir ROUND_BONUS al enum de PostgreSQL
    op.execute(
        "ALTER TYPE movement_type ADD VALUE IF NOT EXISTS 'ROUND_BONUS'"
    )

    op.add_column(
        'leagues',
        sa.Column(
            'last_synced_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        'movements',
        sa.Column(
            'round_number',
            sa.Integer(),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movements', 'round_number')
    op.drop_column('leagues', 'last_synced_at')
    # ### end Alembic commands ###
