"""add biwenger ids

Revision ID: c0a9f887570c
Revises: 6d30a29a6001
Create Date: 2026-08-13 16:23:59.374608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a9f887570c'
down_revision: Union[str, Sequence[str], None] = '6d30a29a6001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_participants', sa.Column('biwenger_user_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint('uq_league_participants_league_id_biwenger_user_id', 'league_participants', ['league_id', 'biwenger_user_id'])
    op.add_column('leagues', sa.Column('biwenger_league_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint('uq_leagues_biwenger_league_id', 'leagues', ['biwenger_league_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_leagues_biwenger_league_id', 'leagues', type_='unique')
    op.drop_column('leagues', 'biwenger_league_id')
    op.drop_constraint('uq_league_participants_league_id_biwenger_user_id', 'league_participants', type_='unique')
    op.drop_column('league_participants', 'biwenger_user_id')
    # ### end Alembic commands ###
